__default__:
    account: ubuntu # your hpc account
    partition: main # the partition you use
    time: 1500 # default time (minutes)
    nodes: 1
    output: "/scratch2/SLURMLOG/{rule}.{wildcards}.out"
    error: "/scratch2/SLURMLOG/{rule}.{wildcards}.err"
    #ntasks: 1
    #mem: 14GB # default memory
   
generate_index:
    mem: 200GB

mapping:
    mem: 200GB

