name:
  rissmed
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - viennarna=2.4.18
  - pip
  - pip:
    - numpy
    - biopython
    - pandas
    - natsort
    - dash
    - dash-bootstrap-components
    - sphinx
    - sphinxcontrib-napoleon
    - sphinx-argparse
    - sphinx_rtd_theme
    - pytest-sphinx
    - docutils
    - doc8
    - autodoc
    - mathjax
    - recommonmark
    - configargparse
    - appdirs
